---
# create volume snapshots
- name: Create volume snapshots
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name}}'
    display_name: "{{ item.vol_name}} - {{ lookup('pipe','date')}}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ volumes }}'