# common
availability_zone: melbourne-qh2-uom
ansible_user: ubuntu
default_ssh_port: 22

# volumes 
volumes: 
  - vol_name: vol-prod-data
    vol_size: 50
  - vol_name: vol-prod-app
    vol_size: 20

volume_snapshot: 'N'

# security group:
security_groups:
  - name: ssh
    description: "SSH Security Group"
  - name: couchdb
    description: "CouchDB security group"
  

# TODO: Create a nested list for security groups - rules
security_group_rules:
  - name: SSH - Allow ingress ssh
    security_group: ssh
    direction: ingress
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Internal cluster communication
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Cluster communication
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Cluster communication External
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 9584
    port_range_max: 9584  
    remote_ip_prefix: 0.0.0.0/0


# Inital instances
instances:
  - name: vm-test
    instance_name: vm-test
    instance_image: cb6d0a36-37f4-47c4-8a82-e201bf667211 
    instance_key_name: gild-nectar
    instance_flavor: 639b8b2a-a5a6-4aa2-8592-ca765ee7af63
    instance_hostname: vm-test
    instance_group: dbservers, appservers
  # - name: vm-prod-db-2
  #   instance_name: vm-prod-db-2
  #   instance_image:  0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5
  #   instance_key_name: gild-nectar
  #   instance_flavor: 639b8b2a-a5a6-4aa2-8592-ca765ee7af63
  #   instance_hostname: vm-prod-db-2
  #   instance_group: dbservers
  # - name: vm-prod-db-3
  #   instance_name: vm-prod-db-3
  #   instance_image:  0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5
  #   instance_key_name: gild-nectar
  #   instance_flavor: 639b8b2a-a5a6-4aa2-8592-ca765ee7af63
  #   instance_hostname: vm-prod-db-3
  #   instance_group: dbservers
  # - name: vm-prod-app-1
  #   instance_name: vm-prod-app-1
  #   instance_image:  0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5
  #   instance_key_name: gild-nectar
  #   instance_flavor: 639b8b2a-a5a6-4aa2-8592-ca765ee7af63
  #   instance_group: appservers


db: 0
app: 0
db_instance_prefix_name: db-dragonstone
app_instance_prefix_name: app-winterfell
instance_image: cb6d0a36-37f4-47c4-8a82-e201bf667211
instance_key_name: gild-nectar
instance_flavor: uom.mse.2c9g
db_instance_group: dbservers
db_instance_security_group: couchdb,ssh
app_instance_security_group: couchdb,ssh
app_instance_group: appservers
db_app_instance_group: 'dbservers,appservers'