# common
availability_zone: melbourne-qh2-uom
ansible_user: ubuntu
ansible_user_password: p01ss0n
default_ssh_port: 22
http_proxy: http://wwwproxy.unimelb.edu.au:8000
https_proxy: http://wwwproxy.unimelb.edu.au:8000
ftp_proxy: http://wwwproxy.unimelb.edu.au:8000
no_proxy: 127.0.0.1,localhost,127.0.1.1,ubuntu

# volumes 

# device data location 
data_volume: /dev/vdb

# volume size
volume_size: 50

# data fstype
volume_fstype: ext4

volume_snapshot: 'N'

# volumes: 
#   - vol_name: vol-db
#     vol_size: 50
  # - vol_name: vol-app
  #   vol_size: 50



# security group:
security_groups:
  - name: ssh
    description: "SSH Security Group"
  - name: couchdb
    description: "CouchDB security group"
  

# TODO: Create a nested list for security groups - rules
security_group_rules:
  - name: SSH - Allow ingress ssh
    security_group: ssh
    direction: ingress
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Internal cluster communication
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Cluster communication
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Cluster communication External
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984  
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB - Cluster communication External (Compatibility)
    security_group: couchdb
    direction: ingress
    protocol: tcp
    port_range_min: 9584
    port_range_max: 9584  
    remote_ip_prefix: 0.0.0.0/0

db: 0
app: 0
db_instance_prefix_name: db-dragonstone
app_instance_prefix_name: app-winterfell
instance_image: 'NeCTAR Ubuntu 16.04 LTS (Xenial) amd64' 
instance_key_name: gild-nectar
instance_flavor: uom.mse.2c9g
db_instance_group: dbservers
db_instance_security_group: couchdb,ssh
app_instance_security_group: ssh
app_instance_group: appservers
db_app_instance_group: 'dbservers,appservers'
 