all:
    vars:
      ansible_ssh_private_key_file: ~/.ssh/gild-nectar.pem
      
    children:
      dev:
        children:
          dbservers:
            hosts:
              host0:
                ansible_host: 115.146.85.179
              host1:
                ansible_host: 115.146.85.220
            
          appservers:
            hosts:
              host1:
                ansible_host: 115.146.85.220
      prod:
        children:
          dbservers:
            hosts:
              host0:
                ansible_host: 115.146.84.108
              host1:
                ansible_host: 115.146.85.20
            
          appservers:
            hosts:
              host1:
                ansible_host: 115.146.85.20