- name: Create databases
  uri:
    url: http://{{ coordinator_node }}:{{ http_api_port }}/{{ item.name }}?n={{ n_replicas }}&q={{ q_shards }}
    method: PUT
    user: "{{ www_user }}"
    password: "{{ www_password }}"
    body: '{}'
    body_format: json
    return_content: yes
    status_code: 201,202,409,412 # status code when it's not failing
    headers:
      Content-Type: "application/json"

  register: result
  run_once: true

  loop: '{{ databases }}'

- name: Populate credential database
  uri:
    url: http://{{ coordinator_node }}:{{ http_api_port }}/{{ credential_db }}/_bulk_docs
    method: POST
    user: "{{ www_user }}"
    password: "{{ www_password }}"
    body: "{{ lookup('file','credentials.json') }}"
    body_format: json
    return_content: yes
    status_code: 201
    headers:
      Content-Type: "application/json"

  register: result
  run_once: true
- name: debug databases
  debug:
    msg: "Databases created with coordinating node: {{ coordinator_node }}: {{ result }}"