- name: Install Transport HTTP
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: System Update
  apt:
    update_cache: yes
    upgrade: dist


# - name: Checking if package erlang is installed
#   shell: dpkg-query -s erlang | grep 'install ok installed'
#   register: is_installed
#   failed_when: no
#   changed_when: no

- name: Download esl erlang package if needed
  get_url:
    url: http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_20.1-1~ubuntu~xenial_amd64.deb
    dest: /home/ubuntu/esl-erlang_20.1-1~ubuntu~xenial_amd64.deb
    owner: ubuntu
    group: ubuntu
    mode: 0755
  #when: is_installed.rc == 0



- name: Install package esl erlang if needed
  apt:
    deb: /home/ubuntu/esl-erlang_20.1-1~ubuntu~xenial_amd64.deb
  #when: is_installed.rc == 0

- name: Download erlang solutions if needed
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /home/ubuntu/erlang-solutions_1.0_all.deb
    owner: ubuntu
    group: ubuntu
    mode: 0755
  #when: is_installed.rc == 0

- name: Install erlang repository if needed
  apt:
    deb: /home/ubuntu/erlang-solutions_1.0_all.deb
  #when: is_installed.rc == 0

- name: Add an Apt signing key
  apt_key:
    url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
    state: present
  #when: is_installed.rc == 0

- name: fix unmet dependencies
  shell: apt-get -f install
  
- name: Add RabbitMQ repo
  shell: echo "deb https://dl.bintray.com/rabbitmq/debian xenial main" | tee /etc/apt/sources.list.d/bintray.rabbitmq.list

- name: add trusted key
  shell: wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc  | apt-key add -
  
- name: System update with new repositories
  apt:
    update_cache: yes
    upgrade: dist

- name: Install RabbitMQ
  apt: 
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: Enable Rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq

- name: Add RabbitMQ user
  rabbitmq_user:
    user: '{{ rabbitmq_admin_user }}'
    password: '{{ rabbitmq_admin_password }}'
    vhost: /
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

