- name: Set authorized key taken from file
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: "{{ lookup('file', '{{ item.file_name }}') }}"
  loop: '{{ keys }}'

- name: Add to known hosts if possible
  known_hosts:
    path: ~/.ssh/known_hosts
    name: '{{ ansible_host }}'
    key: "{{ lookup('file', '{{ item.file_name }}') }}"
    state: present
  loop: '{{ keys }}'
  failed_when: false