---
- name: Grant internet access - http
  lineinfile:
    dest: /etc/environment
    insertafter: '^\[PATH\]$'
    line: 'http_proxy="{{ http_proxy }}"'

- name: Grant internet access - https
  lineinfile:
    dest: /etc/environment
    insertafter: '^\[PATH\]$'
    line: 'https_proxy="{{ https_proxy }}"'

- name: Grant internet access - ftp
  lineinfile:
    dest: /etc/environment
    insertafter: '^\[PATH\]$'
    line: 'ftp_proxy="{{ ftp_proxy }}"'

- name: Grant internet access - no proxy
  lineinfile:
    dest: /etc/environment
    insertafter: '^\[PATH\]$'
    line: 'no_proxy="{{ no_proxy }},{{ ansible_host }}"'

- name: Install dependencies
  apt:
    name: 
      - openssl
      - python3-pip
      - python3-all-dev
      - python3-setuptools
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Setup python 3 as default
  file: 
    src: '/usr/bin/python3.5' 
    dest: '/usr/bin/python'
    state: link 
    force: yes
