# TODO: Add proper validation when request fails
# TODO: Set up variable coordination node correctly
- name: Join - master node
  uri:
    url: http://45.113.233.248:9584/_cluster_setup
    method: POST
    user: "admin"
    password: "password"
    body: '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 9584, "node_count": "2", "remote_node": "{{ ansible_host }}", "remote_current_user": "admin", "remote_current_password": "password" }'
    body_format: json
    status_code: 201
    return_content: yes
    headers:
      Content-Type: "application/json"
  failed_when: false
    #with_items:  groups['dbservers_cluster_master']

- name: Join - other nodes
  uri:
    url: http://45.113.233.248:9584:9584/_cluster_setup
    method: POST
    user: "admin"
    password: "password"
    body: '{"action": "add_node", "host":"{{ ansible_host }}", "port": 9584, "username": "admin", "password":"password"}'
    body_format: json
    status_code: 201
    return_content: yes
    headers:
      Content-Type: "application/json"
  register: json_response
  failed_when: false
  #with_items:  groups['dbservers_cluster_node']

- name: Finish cluster
  uri:
    url: http://{{ ansible_host }}:9584/_cluster_setup 
    method: POST
    user: "admin"
    password: "password"
    body: '{"action": "finish_cluster"}'
    body_format: json
    status_code: 201
    return_content: yes
    headers:
      Content-Type: "application/json"
  failed_when: false
  register: json_response