- name: Install dependencies for analytics
  apt:
    name: 
      - npm 
      - nodejs
      - nodejs-legacy
      
      #- nodejs-legacy
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install jupyterhub requirements
  npm:
      name: configurable-http-proxy
      global: yes

- name: Deploy app from repo
  git:
      repo: '{{ repo }}'
      dest: '{{ appsrc }}'
      version: '{{ version }}'

- name: Upgrading notebooks
  pip:
      name: notebook
      extra_args: --upgrade

- name: Install requirements
  pip: 
      requirements: '{{ appsrc }}/requirements.txt'
      executable: pip3

- name: Downloading NLTK data
  shell: "python -m nltk.downloader stopwords && python -m nltk.downloader vader_lexicon && python -m nltk.downloader punkt"
  become: yes
  become_user: '{{ ansible_user }}'

- name: Downloading NLTK data
  shell: "python -m nltk.downloader stopwords && python -m nltk.downloader vader_lexicon && python -m nltk.downloader punkt"
  become: yes
  become_user: '{{ ansible_user }}'