all:
    vars:
      ansible_ssh_private_key_file: ~/.ssh/gild-nectar.pem
    children:
      dev:
        children:
          dbservers:
            hosts:
              host0:
                ansible_host: 115.146.85.179
                ansible_user: ubuntu
              host1:
                ansible_host: 115.146.85.220
                ansible_user: ubuntu
          appservers:
            hosts:
              host1:
                ansible_host: 115.146.85.220
                ansible_user: ubuntu
    