- hosts: appserver
  vars_files:
    - host_vars/nectar.yml
    - group_vars/appserver.yml
    - group_vars/dbservers.yml

  gather_facts: true
  
  roles: 
    - role: openstack-sshkeys
    - role: openstack-common
    - role: analytics-common
    - role: analytics-appserver