- hosts: localhost
  vars_files:
    - host_vars/nectar.yml
  vars: 
    - db_num_servers: '{{ db }}'
    - app_num_servers: '{{ app }}'
    - all_num_servers: '{{ all }}'
    - vol_snapshot: '{{ volume_snapshot }}'
    - total_db_servers: "{{ groups['dbservers']|default([]) | length }}"
    - total_app_servers: "{{ groups['appservers']|default([]) | length }}"
    - total_all_servers: "{{ groups['all']|default([]) | length }}"
  gather_facts: true

  pre_tasks:
    - name: Starting cloud
      debug:
        msg: all="{{ all }}" db="{{ db }}" app="{{ app }}"

    
  roles: 
    
    - role: openstack-security-group
    - role: openstack-instance
    - {role: openstack-volume, when: db > 0}
    - {role: openstack-volume-snapshot, when: vol_snapshot  == 'Y' }
