- hosts: localhost
  vars_files:
    - host_vars/nectar.yml
  vars: 
    - server_profiles: '{{ profiles }}'
  gather_facts: true

  pre_tasks:
    - name: Scaling cloud
      debug:
        msg: '{{ profiles }}''

    
  roles: 
    
    - role: openstack-security-group
    - role: openstack-instance
    - {role: openstack-volume, when: db > 0}
    - {role: openstack-volume-snapshot, when: vol_snapshot  == 'Y' }
