- hosts: localhost
  vars_files:
    - host_vars/nectar.yml
  vars:
    - instances: '{{ instances }}'
  gather_facts: true

  pre_tasks:
    - name: Setting up cloud
      debug:
        msg: '{{ instances }}'

  roles: 
    
     - role: openstack-security-group
     - role: openstack-instance 
     - role: openstack-volume
     - {role: openstack-volume-snapshot, when: volume_snapshot  == 'Y' }

  post_tasks:

    - name: Refresh in-memory Inventory
      meta: refresh_inventory

    

    - name: Wait for ssh connection
      become: false
      wait_for:
        port: 22
        delay: 2
        connect_timeout: 10
        timeout: 600
        host: "{{ hostvars[item]['ansible_host'] }}"
      loop: "{{groups['all']}}"
    
    
